---@class lsp.CompletionItem

---@type lsp.CompletionItem[]
return {
    {
        text = ":art:",
        kind = 20,
        label = " 🎨 Improve structure / format of the code",
        documentation = {
            kind = "plaintext",
            value = "(:art:)",
        },
        emoji = "🎨",
        filterText = ":art: Improve structure / format of the code",
        insertText = "",
    },
    {
        text = ":zap:",
        kind = 20,
        label = " ⚡ Improve performance",
        documentation = {
            kind = "plaintext",
            value = "(:zap:)",
        },
        emoji = "⚡",
        filterText = ":zap: Improve performance",
        insertText = "",
    },
    {
        text = ":fire:",
        kind = 20,
        label = " 🔥 Remove code or files",
        documentation = {
            kind = "plaintext",
            value = "(:fire:)",
        },
        emoji = "🔥",
        filterText = ":fire: Remove code or files",
        insertText = "",
    },
    {
        text = ":bug:",
        kind = 20,
        label = " 🐛 Fix a bug",
        documentation = {
            kind = "plaintext",
            value = "(:bug:)",
        },
        emoji = "🐛",
        filterText = ":bug: Fix a bug",
        insertText = "",
    },
    {
        text = ":ambulance:",
        kind = 20,
        label = " 🚑 Critical hotfix",
        documentation = {
            kind = "plaintext",
            value = "(:ambulance:)",
        },
        emoji = "🚑",
        filterText = ":ambulance: Critical hotfix",
        insertText = "",
    },
    {
        text = ":sparkles:",
        kind = 20,
        label = " ✨ Introduce new features",
        documentation = {
            kind = "plaintext",
            value = "(:sparkles:)",
        },
        emoji = "✨",
        filterText = ":sparkles: Introduce new features",
        insertText = "",
    },
    {
        text = ":memo:",
        kind = 20,
        label = " 📝 Add or update documentation",
        documentation = {
            kind = "plaintext",
            value = "(:memo:)",
        },
        emoji = "📝",
        filterText = ":memo: Add or update documentation",
        insertText = "",
    },
    {
        text = ":rocket:",
        kind = 20,
        label = " 🚀 Deploy stuff!",
        documentation = {
            kind = "plaintext",
            value = "(:rocket:)",
        },
        emoji = "🚀",
        filterText = ":rocket: Deploy stuff!",
        insertText = "",
    },
    {
        text = ":lipstick:",
        kind = 20,
        label = " 💄 Add or update the UI and style files",
        documentation = {
            kind = "plaintext",
            value = "(:lipstick:)",
        },
        emoji = "💄",
        filterText = ":lipstick: Add or update the UI and style files",
        insertText = "",
    },
    {
        text = ":tada:",
        kind = 20,
        label = " 🎉 Begin a project",
        documentation = {
            kind = "plaintext",
            value = "(:tada:)",
        },
        emoji = "🎉",
        filterText = ":tada: Begin a project",
        insertText = "",
    },
    {
        text = ":white_check_mark:",
        kind = 20,
        label = " ✅ Add, update, or pass tests",
        documentation = {
            kind = "plaintext",
            value = "(:white_check_mark:)",
        },
        emoji = "✅",
        filterText = ":white_check_mark: Add, update, or pass tests",
        insertText = "",
    },
    {
        text = ":lock:",
        kind = 20,
        label = " 🔒️ Fix security issues",
        documentation = {
            kind = "plaintext",
            value = "(:lock:)",
        },
        emoji = "🔒️",
        filterText = ":lock: Fix security issues",
        insertText = "",
    },
    {
        text = ":closed_lock_with_key:",
        kind = 20,
        label = " 🔐 Add or update secrets",
        documentation = {
            kind = "plaintext",
            value = "(:closed_lock_with_key:)",
        },
        emoji = "🔐",
        filterText = ":closed_lock_with_key: Add or update secrets",
        insertText = "",
    },
    {
        text = ":bookmark:",
        kind = 20,
        label = " 🔖 Release / Version tags",
        documentation = {
            kind = "plaintext",
            value = "(:bookmark:)",
        },
        emoji = "🔖",
        filterText = ":bookmark: Release / Version tags",
        insertText = "",
    },
    {
        text = ":rotating_light:",
        kind = 20,
        label = " 🚨 Fix compiler / linter warnings",
        documentation = {
            kind = "plaintext",
            value = "(:rotating_light:)",
        },
        emoji = "🚨",
        filterText = ":rotating_light: Fix compiler / linter warnings",
        insertText = "",
    },
    {
        text = ":construction:",
        kind = 20,
        label = " 🚧 Work in progress",
        documentation = {
            kind = "plaintext",
            value = "(:construction:)",
        },
        emoji = "🚧",
        filterText = ":construction: Work in progress",
        insertText = "",
    },
    {
        text = ":green_heart:",
        kind = 20,
        label = " 💚 Fix CI Build",
        documentation = {
            kind = "plaintext",
            value = "(:green_heart:)",
        },
        emoji = "💚",
        filterText = ":green_heart: Fix CI Build",
        insertText = "",
    },
    {
        text = ":arrow_down:",
        kind = 20,
        label = " ⬇️  Downgrade dependencies",
        documentation = {
            kind = "plaintext",
            value = "(:arrow_down:)",
        },
        emoji = "⬇️",
        filterText = ":arrow_down: Downgrade dependencies",
        insertText = "",
    },
    {
        text = ":arrow_up:",
        kind = 20,
        label = " ⬆️ Upgrade dependencies",
        documentation = {
            kind = "plaintext",
            value = "(:arrow_up:)",
        },
        emoji = "⬆️",
        filterText = ":arrow_up: Upgrade dependencies",
        insertText = "",
    },
    {
        text = ":pushpin:",
        kind = 20,
        label = " 📌 Pin dependencies to specific versions",
        documentation = {
            kind = "plaintext",
            value = "(:pushpin:)",
        },
        emoji = "📌",
        filterText = ":pushpin: Pin dependencies to specific versions",
        insertText = "",
    },
    {
        text = ":construction_worker:",
        kind = 20,
        label = " 👷 Add or update CI build system",
        documentation = {
            kind = "plaintext",
            value = "(:construction_worker:)",
        },
        emoji = "👷",
        filterText = ":construction_worker: Add or update CI build system",
        insertText = "",
    },
    {
        text = ":chart_with_upwards_trend:",
        kind = 20,
        label = " 📈 Add or update analytics or track code",
        documentation = {
            kind = "plaintext",
            value = "(:chart_with_upwards_trend:)",
        },
        emoji = "📈",
        filterText = ":chart_with_upwards_trend: Add or update analytics or track code",
        insertText = "",
    },
    {
        text = ":recycle:",
        kind = 20,
        label = " ♻️  Refactor code",
        documentation = {
            kind = "plaintext",
            value = "(:recycle:)",
        },
        emoji = "♻️",
        filterText = ":recycle: Refactor code",
        insertText = "",
    },
    {
        text = ":heavy_plus_sign:",
        kind = 20,
        label = " ➕ Add a dependency",
        documentation = {
            kind = "plaintext",
            value = "(:heavy_plus_sign:)",
        },
        emoji = "➕",
        filterText = ":heavy_plus_sign: Add a dependency",
        insertText = "",
    },
    {
        text = ":heavy_minus_sign:",
        kind = 20,
        label = " ➖ Remove a dependency",
        documentation = {
            kind = "plaintext",
            value = "(:heavy_minus_sign:)",
        },
        emoji = "➖",
        filterText = ":heavy_minus_sign: Remove a dependency",
        insertText = "",
    },
    {
        text = ":wrench:",
        kind = 20,
        label = " 🔧 Add or update configuration files",
        documentation = {
            kind = "plaintext",
            value = "(:wrench:)",
        },
        emoji = "🔧",
        filterText = ":wrench: Add or update configuration files",
        insertText = "",
    },
    {
        text = ":hammer:",
        kind = 20,
        label = " 🔨 Add or update development scripts",
        documentation = {
            kind = "plaintext",
            value = "(:hammer:)",
        },
        emoji = "🔨",
        filterText = ":hammer: Add or update development scripts",
        insertText = "",
    },
    {
        text = ":globe_with_meridans:",
        kind = 20,
        label = " 🌐 Internationalization and localization",
        documentation = {
            kind = "plaintext",
            value = "(:globe_with_meridans:)",
        },
        emoji = "🌐",
        filterText = ":globe_with_meridans: Internationalization and localization",
        insertText = "",
    },
    {
        text = ":pencil2:",
        kind = 20,
        label = " ✏️  Fix typos",
        documentation = {
            kind = "plaintext",
            value = "(:pencil2:)",
        },
        emoji = "✏️",
        filterText = ":pencil2: Fix typos",
        insertText = "",
    },
    {
        text = ":poop:",
        kind = 20,
        label = " 💩 Write bad code that needs to be improved",
        documentation = {
            kind = "plaintext",
            value = "(:poop:)",
        },
        emoji = "💩",
        filterText = ":poop: Write bad code that needs to be improved",
        insertText = "",
    },
    {
        text = ":rewind:",
        kind = 20,
        label = " ⏪️ Revert changes",
        documentation = {
            kind = "plaintext",
            value = "(:rewind:)",
        },
        emoji = "⏪️",
        filterText = ":rewind: Revert changes",
        insertText = "",
    },
    {
        text = ":twisted_rightwards_arrows:",
        kind = 20,
        label = " 🔀 Merge branches",
        documentation = {
            kind = "plaintext",
            value = "(:twisted_rightwards_arrows:)",
        },
        emoji = "🔀",
        filterText = ":twisted_rightwards_arrows: Merge branches",
        insertText = "",
    },
    {
        text = ":package:",
        kind = 20,
        label = " 📦️ Add or update compiled files or packages",
        documentation = {
            kind = "plaintext",
            value = "(:package:)",
        },
        emoji = "📦️",
        filterText = ":package: Add or update compiled files or packages",
        insertText = "",
    },
    {
        text = ":alien:",
        kind = 20,
        label = " 👽️ Update code due to external API changes",
        documentation = {
            kind = "plaintext",
            value = "(:alien:)",
        },
        emoji = "👽️",
        filterText = ":alien: Update code due to external API changes",
        insertText = "",
    },
    {
        text = ":truck:",
        kind = 20,
        label = " 🚚 Move or rename resources (e.g.: files, paths, routes)",
        documentation = {
            kind = "plaintext",
            value = "(:truck:)",
        },
        emoji = "🚚",
        filterText = ":truck: Move or rename resources (e.g.: files, paths, routes)",
        insertText = "",
    },
    {
        text = ":page_facing_up:",
        kind = 20,
        label = " 📄 Add or update license",
        documentation = {
            kind = "plaintext",
            value = "(:page_facing_up:)",
        },
        emoji = "📄",
        filterText = ":page_facing_up: Add or update license",
        insertText = "",
    },
    {
        text = ":boom:",
        kind = 20,
        label = " 💥 Introduce breaking changes",
        documentation = {
            kind = "plaintext",
            value = "(:boom:)",
        },
        emoji = "💥",
        filterText = ":boom: Introduce breaking changes",
        insertText = "",
    },
    {
        text = ":bento:",
        kind = 20,
        label = " 🍱 Add or update assets",
        documentation = {
            kind = "plaintext",
            value = "(:bento:)",
        },
        emoji = "🍱",
        filterText = ":bento: Add or update assets",
        insertText = "",
    },
    {
        text = ":wheelchair:",
        kind = 20,
        label = " ♿️ Improve accessibility",
        documentation = {
            kind = "plaintext",
            value = "(:wheelchair:)",
        },
        emoji = "♿️",
        filterText = ":wheelchair: Improve accessibility",
        insertText = "",
    },
    {
        text = ":bulb:",
        kind = 20,
        label = " 💡 Add or update comments in source code",
        documentation = {
            kind = "plaintext",
            value = "(:bulb:)",
        },
        emoji = "💡",
        filterText = ":bulb: Add or update comments in source code",
        insertText = "",
    },
    {
        text = ":beers:",
        kind = 20,
        label = " 🍻 Write code drunkenly",
        documentation = {
            kind = "plaintext",
            value = "(:beers:)",
        },
        emoji = "🍻",
        filterText = ":beers: Write code drunkenly",
        insertText = "",
    },
    {
        text = ":speech_balloon:",
        kind = 20,
        label = " 💬 Add or update text and literals",
        documentation = {
            kind = "plaintext",
            value = "(:speech_balloon:)",
        },
        emoji = "💬",
        filterText = ":speech_balloon: Add or update text and literals",
        insertText = "",
    },
    {
        text = ":card_file_box:",
        kind = 20,
        label = " 🗃️ Perform database related changes",
        documentation = {
            kind = "plaintext",
            value = "(:card_file_box:)",
        },
        emoji = "🗃️",
        filterText = ":card_file_box: Perform database related changes",
        insertText = "",
    },
    {
        text = ":loud_sound:",
        kind = 20,
        label = " 🔊 Add or update logs",
        documentation = {
            kind = "plaintext",
            value = "(:loud_sound:)",
        },
        emoji = "🔊",
        filterText = ":loud_sound: Add or update logs",
        insertText = "",
    },
    {
        text = ":mute:",
        kind = 20,
        label = " 🔇 Remove logs",
        documentation = {
            kind = "plaintext",
            value = "(:mute:)",
        },
        emoji = "🔇",
        filterText = ":mute: Remove logs",
        insertText = "",
    },
    {
        text = ":busts_in_silhouette:",
        kind = 20,
        label = " 👥 Add or update contributor(s)",
        documentation = {
            kind = "plaintext",
            value = "(:busts_in_silhouette:)",
        },
        emoji = "👥",
        filterText = ":busts_in_silhouette: Add or update contributor(s)",
        insertText = "",
    },
    {
        text = ":children_crossing:",
        kind = 20,
        label = " 🚸 Improve user experience / usability",
        documentation = {
            kind = "plaintext",
            value = "(:children_crossing:)",
        },
        emoji = "🚸",
        filterText = ":children_crossing: Improve user experience / usability",
        insertText = "",
    },
    {
        text = ":building_contruction:",
        kind = 20,
        label = " 🏗️ Make architectural changes",
        documentation = {
            kind = "plaintext",
            value = "(:building_contruction:)",
        },
        emoji = "🏗️",
        filterText = ":building_contruction: Make architectural changes",
        insertText = "",
    },
    {
        text = ":iphone:",
        kind = 20,
        label = " 📱 Work on responsive design",
        documentation = {
            kind = "plaintext",
            value = "(:iphone:)",
        },
        emoji = "📱",
        filterText = ":iphone: Work on responsive design",
        insertText = "",
    },
    {
        text = ":clown:",
        kind = 20,
        label = " 🤡 Mock things",
        documentation = {
            kind = "plaintext",
            value = "(:clown:)",
        },
        emoji = "🤡",
        filterText = ":clown: Mock things",
        insertText = "",
    },
    {
        text = ":egg:",
        kind = 20,
        label = " 🥚 Add or update an easter egg",
        documentation = {
            kind = "plaintext",
            value = "(:egg:)",
        },
        emoji = "🥚",
        filterText = ":egg: Add or update an easter egg",
        insertText = "",
    },
    {
        text = ":see_no_evil:",
        kind = 20,
        label = " 🙈 Add or update a .gitignore file",
        documentation = {
            kind = "plaintext",
            value = "(:see_no_evil:)",
        },
        emoji = "🙈",
        filterText = ":see_no_evil: Add or update a .gitignore file",
        insertText = "",
    },
    {
        text = ":camera_flash:",
        kind = 20,
        label = " 📸 Add or update snapshots",
        documentation = {
            kind = "plaintext",
            value = "(:camera_flash:)",
        },
        emoji = "📸",
        filterText = ":camera_flash: Add or update snapshots",
        insertText = "",
    },
    {
        text = ":alembic:",
        kind = 20,
        label = " ⚗️  Perform experiments",
        documentation = {
            kind = "plaintext",
            value = "(:alembic:)",
        },
        emoji = "⚗️",
        filterText = ":alembic: Perform experiments",
        insertText = "",
    },
    {
        text = ":mag:",
        kind = 20,
        label = " 🔍️ Improve SEO",
        documentation = {
            kind = "plaintext",
            value = "(:mag:)",
        },
        emoji = "🔍️",
        filterText = ":mag: Improve SEO",
        insertText = "",
    },
    {
        text = ":label:",
        kind = 20,
        label = " 🏷️ Add or update types",
        documentation = {
            kind = "plaintext",
            value = "(:label:)",
        },
        emoji = "🏷️",
        filterText = ":label: Add or update types",
        insertText = "",
    },
    {
        text = ":seedling:",
        kind = 20,
        label = " 🌱 Add or update seed files",
        documentation = {
            kind = "plaintext",
            value = "(:seedling:)",
        },
        emoji = "🌱",
        filterText = ":seedling: Add or update seed files",
        insertText = "",
    },
    {
        text = ":triangular_flag_on_pole:",
        kind = 20,
        label = " 🚩 Add, update, or remove feature flags",
        documentation = {
            kind = "plaintext",
            value = "(:triangular_flag_on_pole:)",
        },
        emoji = "🚩",
        filterText = ":triangular_flag_on_pole: Add, update, or remove feature flags",
        insertText = "",
    },
    {
        text = ":goal_net:",
        kind = 20,
        label = " 🥅 Catch errors",
        documentation = {
            kind = "plaintext",
            value = "(:goal_net:)",
        },
        emoji = "🥅",
        filterText = ":goal_net: Catch errors",
        insertText = "",
    },
    {
        text = ":dizzy:",
        kind = 20,
        label = " 💫 Add or update animations and transitions",
        documentation = {
            kind = "plaintext",
            value = "(:dizzy:)",
        },
        emoji = "💫",
        filterText = ":dizzy: Add or update animations and transitions",
        insertText = "",
    },
    {
        text = ":wastebucket:",
        kind = 20,
        label = " 🗑️ Deprecate code that needs to be cleaned up",
        documentation = {
            kind = "plaintext",
            value = "(:wastebucket:)",
        },
        emoji = "🗑️",
        filterText = ":wastebucket: Deprecate code that needs to be cleaned up",
        insertText = "",
    },
    {
        text = ":passport_control:",
        kind = 20,
        label = " 🛂 Work on code related to authorization, roles and permissions",
        documentation = {
            kind = "plaintext",
            value = "(:passport_control:)",
        },
        emoji = "🛂",
        filterText = ":passport_control: Work on code related to authorization, roles and permissions",
        insertText = "",
    },
    {
        text = ":adhesive_bandage:",
        kind = 20,
        label = " 🩹 Simple fix for a non-critical issue",
        documentation = {
            kind = "plaintext",
            value = "(:adhesive_bandage:)",
        },
        emoji = "🩹",
        filterText = ":adhesive_bandage: Simple fix for a non-critical issue",
        insertText = "",
    },
    {
        text = ":monocle_face:",
        kind = 20,
        label = " 🧐 Data exploration/inspection",
        documentation = {
            kind = "plaintext",
            value = "(:monocle_face:)",
        },
        emoji = "🧐",
        filterText = ":monocle_face: Data exploration/inspection",
        insertText = "",
    },
    {
        text = ":coffin:",
        kind = 20,
        label = " ⚰️  Remove dead code",
        documentation = {
            kind = "plaintext",
            value = "(:coffin:)",
        },
        emoji = "⚰️",
        filterText = ":coffin: Remove dead code",
        insertText = "",
    },
    {
        text = ":test_tube:",
        kind = 20,
        label = " 🧪 Add a failing test",
        documentation = {
            kind = "plaintext",
            value = "(:test_tube:)",
        },
        emoji = "🧪",
        filterText = ":test_tube: Add a failing test",
        insertText = "",
    },
    {
        text = ":necktie:",
        kind = 20,
        label = " 👔 Add or update business logic",
        documentation = {
            kind = "plaintext",
            value = "(:necktie:)",
        },
        emoji = "👔",
        filterText = ":necktie: Add or update business logic",
        insertText = "",
    },
    {
        text = ":stethoscope:",
        kind = 20,
        label = " 🩺 Add or update healthcheck",
        documentation = {
            kind = "plaintext",
            value = "(:stethoscope:)",
        },
        emoji = "🩺",
        filterText = ":stethoscope: Add or update healthcheck",
        insertText = "",
    },
    {
        text = ":bricks:",
        kind = 20,
        label = " 🧱 Infrastructure related changes",
        documentation = {
            kind = "plaintext",
            value = "(:bricks:)",
        },
        emoji = "🧱",
        filterText = ":bricks: Infrastructure related changes",
        insertText = "",
    },
    {
        text = ":technologist:",
        kind = 20,
        label = " 🧑💻 Improve developer experience",
        documentation = {
            kind = "plaintext",
            value = "(:technologist:)",
        },
        emoji = "🧑💻",
        filterText = ":technologist: Improve developer experience",
        insertText = "",
    },
    {
        text = ":money_with_wings:",
        kind = 20,
        label = " 💸 Add sponsorships or money related infrastructure",
        documentation = {
            kind = "plaintext",
            value = "(:money_with_wings:)",
        },
        emoji = "💸",
        filterText = ":money_with_wings: Add sponsorships or money related infrastructure",
        insertText = "",
    },
    {
        text = ":thread:",
        kind = 20,
        label = " 🧵 Add or update code related to multithreading or concurrency",
        documentation = {
            kind = "plaintext",
            value = "(:thread:)",
        },
        emoji = "🧵",
        filterText = ":thread: Add or update code related to multithreading or concurrency",
        insertText = "",
    },
    {
        text = ":safety_vest:",
        kind = 20,
        label = " 🦺 Add or update code related to validation",
        documentation = {
            kind = "plaintext",
            value = "(:safety_vest:)",
        },
        emoji = "🦺",
        filterText = ":safety_vest: Add or update code related to validation",
        insertText = "",
    },
}
