return {
	{
		word = ":art:",
		kind = 20,
		label = " 🎨 Improve structure / format of the code",
		documentation = {
			kind = "plaintext",
			value = "(:art:)",
		},
		insertText = "🎨",
		filterText = ":art: Improve structure / format of the code",
	},
	{
		word = ":zap:",
		kind = 20,
		label = " ⚡ Improve performance ",
		documentation = {
			kind = "plaintext",
			value = "(:zap:)",
		},
		insertText = "⚡",
		filterText = ":zap: Improve performance ",
	},
	{
		word = ":fire:",
		kind = 20,
		label = " 🔥 Remove code or files",
		documentation = {
			kind = "plaintext",
			value = "(:fire:)",
		},
		insertText = "🔥",
		filterText = ":fire: Remove code or files",
	},
	{
		word = ":bug:",
		kind = 20,
		label = " 🐛 Fix a bug",
		documentation = {
			kind = "plaintext",
			value = "(:bug:)",
		},
		insertText = "🐛",
		filterText = ":bug: Fix a bug",
	},
	{
		word = ":ambulance:",
		kind = 20,
		label = " 🚑 Critical hotfix",
		documentation = {
			kind = "plaintext",
			value = "(:ambulance:)",
		},
		insertText = "🚑",
		filterText = ":ambulance: Critical hotfix",
	},
	{
		word = ":sparkles:",
		kind = 20,
		label = " ✨ Introduce new features",
		documentation = {
			kind = "plaintext",
			value = "(:sparkles:)",
		},
		insertText = "✨",
		filterText = ":sparkles: Introduce new features",
	},
	{
		word = ":memo:",
		kind = 20,
		label = " 📝 Add or update documentation",
		documentation = {
			kind = "plaintext",
			value = "(:memo:)",
		},
		insertText = "📝",
		filterText = ":memo: Add or update documentation",
	},
	{
		word = ":rocket:",
		kind = 20,
		label = " 🚀 Deploy stuff!",
		documentation = {
			kind = "plaintext",
			value = "(:rocket:)",
		},
		insertText = "🚀",
		filterText = ":rocket: Deploy stuff!",
	},
	{
		word = ":lipstick:",
		kind = 20,
		label = " 💄 Add or update the UI and style files",
		documentation = {
			kind = "plaintext",
			value = "(:lipstick:)",
		},
		insertText = "💄",
		filterText = ":lipstick: Add or update the UI and style files",
	},
	{
		word = ":tada:",
		kind = 20,
		label = " 🎉 Begin a project",
		documentation = {
			kind = "plaintext",
			value = "(:tada:)",
		},
		insertText = "🎉",
		filterText = ":tada: Begin a project",
	},
	{
		word = ":white_check_mark:",
		kind = 20,
		label = " ✅ Add, update, or pass tests",
		documentation = {
			kind = "plaintext",
			value = "(:white_check_mark:)",
		},
		insertText = "✅",
		filterText = ":white_check_mark: Add, update, or pass tests",
	},
	{
		word = ":lock:",
		kind = 20,
		label = " 🔒️ Fix security issues",
		documentation = {
			kind = "plaintext",
			value = "(:lock:)",
		},
		insertText = "🔒️",
		filterText = ":lock: Fix security issues",
	},
	{
		word = ":closed_lock_with_key:",
		kind = 20,
		label = " 🔐 Add or update secrets",
		documentation = {
			kind = "plaintext",
			value = "(:closed_lock_with_key:)",
		},
		insertText = "🔐",
		filterText = ":closed_lock_with_key: Add or update secrets",
	},
	{
		word = ":bookmark:",
		kind = 20,
		label = " 🔖 Release / Version tags",
		documentation = {
			kind = "plaintext",
			value = "(:bookmark:)",
		},
		insertText = "🔖",
		filterText = ":bookmark: Release / Version tags",
	},
	{
		word = ":rotating_light:",
		kind = 20,
		label = " 🚨 Fix compiler / linter warnings",
		documentation = {
			kind = "plaintext",
			value = "(:rotating_light:)",
		},
		insertText = "🚨",
		filterText = ":rotating_light: Fix compiler / linter warnings",
	},
	{
		word = ":construction:",
		kind = 20,
		label = " 🚧 Work in progress",
		documentation = {
			kind = "plaintext",
			value = "(:construction:)",
		},
		insertText = "🚧",
		filterText = ":construction: Work in progress",
	},
	{
		word = ":green_heart:",
		kind = 20,
		label = " 💚 Fix CI Build",
		documentation = {
			kind = "plaintext",
			value = "(:green_heart:)",
		},
		insertText = "💚",
		filterText = ":green_heart: Fix CI Build",
	},
	{
		word = ":arrow_down:",
		kind = 20,
		label = " ⬇️  Downgrade dependencies",
		documentation = {
			kind = "plaintext",
			value = "(:arrow_down:)",
		},
		insertText = "⬇️",
		filterText = ":arrow_down: Downgrade dependencies",
	},
	{
		word = ":arrow_up:",
		kind = 20,
		label = " ⬆️ Upgrade dependencies",
		documentation = {
			kind = "plaintext",
			value = "(:arrow_up:)",
		},
		insertText = "⬆️",
		filterText = ":arrow_up: Upgrade dependencies",
	},
	{
		word = ":pushpin:",
		kind = 20,
		label = " 📌 Pin dependencies to specific versions",
		documentation = {
			kind = "plaintext",
			value = "(:pushpin:)",
		},
		insertText = "📌",
		filterText = ":pushpin: Pin dependencies to specific versions",
	},
	{
		word = ":construction_worker:",
		kind = 20,
		label = " 👷 Add or update CI build system",
		documentation = {
			kind = "plaintext",
			value = "(:construction_worker:)",
		},
		insertText = "👷",
		filterText = ":construction_worker: Add or update CI build system",
	},
	{
		word = ":chart_with_upwards_trend:",
		kind = 20,
		label = " 📈 Add or update analytics or track code",
		documentation = {
			kind = "plaintext",
			value = "(:chart_with_upwards_trend:)",
		},
		insertText = "📈",
		filterText = ":chart_with_upwards_trend: Add or update analytics or track code",
	},
	{
		word = ":recycle:",
		kind = 20,
		label = " ♻️  Refactor code",
		documentation = {
			kind = "plaintext",
			value = "(:recycle:)",
		},
		insertText = "♻️",
		filterText = ":recycle: Refactor code",
	},
	{
		word = ":heavy_plus_sign:",
		kind = 20,
		label = " ➕ Add a dependency",
		documentation = {
			kind = "plaintext",
			value = "(:heavy_plus_sign:)",
		},
		insertText = "➕",
		filterText = ":heavy_plus_sign: Add a dependency",
	},
	{
		word = ":heavy_minus_sign:",
		kind = 20,
		label = " ➖ Remove a dependency",
		documentation = {
			kind = "plaintext",
			value = "(:heavy_minus_sign:)",
		},
		insertText = "➖",
		filterText = ":heavy_minus_sign: Remove a dependency",
	},
	{
		word = ":wrench:",
		kind = 20,
		label = " 🔧 Add or update configuration files",
		documentation = {
			kind = "plaintext",
			value = "(:wrench:)",
		},
		insertText = "🔧",
		filterText = ":wrench: Add or update configuration files",
	},
	{
		word = ":hammer:",
		kind = 20,
		label = " 🔨 Add or update development scripts",
		documentation = {
			kind = "plaintext",
			value = "(:hammer:)",
		},
		insertText = "🔨",
		filterText = ":hammer: Add or update development scripts",
	},
	{
		word = ":globe_with_meridans:",
		kind = 20,
		label = " 🌐 Internationalization and localization",
		documentation = {
			kind = "plaintext",
			value = "(:globe_with_meridans:)",
		},
		insertText = "🌐",
		filterText = ":globe_with_meridans: Internationalization and localization",
	},
	{
		word = ":pencil2:",
		kind = 20,
		label = " ✏️  Fix typos",
		documentation = {
			kind = "plaintext",
			value = "(:pencil2:)",
		},
		insertText = "✏️",
		filterText = ":pencil2: Fix typos",
	},
	{
		word = ":poop:",
		kind = 20,
		label = " 💩 Write bad code that needs to be improved",
		documentation = {
			kind = "plaintext",
			value = "(:poop:)",
		},
		insertText = "💩",
		filterText = ":poop: Write bad code that needs to be improved",
	},
	{
		word = ":rewind:",
		kind = 20,
		label = " ⏪️ Revert changes",
		documentation = {
			kind = "plaintext",
			value = "(:rewind:)",
		},
		insertText = "⏪️",
		filterText = ":rewind: Revert changes",
	},
	{
		word = ":twisted_rightwards_arrows:",
		kind = 20,
		label = " 🔀 Merge branches",
		documentation = {
			kind = "plaintext",
			value = "(:twisted_rightwards_arrows:)",
		},
		insertText = "🔀",
		filterText = ":twisted_rightwards_arrows: Merge branches",
	},
	{
		word = ":package:",
		kind = 20,
		label = " 📦️ Add or update compiled files or packages",
		documentation = {
			kind = "plaintext",
			value = "(:package:)",
		},
		insertText = "📦️",
		filterText = ":package: Add or update compiled files or packages",
	},
	{
		word = ":alien:",
		kind = 20,
		label = " 👽️ Update code due to external API changes",
		documentation = {
			kind = "plaintext",
			value = "(:alien:)",
		},
		insertText = "👽️",
		filterText = ":alien: Update code due to external API changes",
	},
	{
		word = ":truck:",
		kind = 20,
		label = " 🚚 Move or rename resources (e.g.: files, paths, routes)",
		documentation = {
			kind = "plaintext",
			value = "(:truck:)",
		},
		insertText = "🚚",
		filterText = ":truck: Move or rename resources (e.g.: files, paths, routes)",
	},
	{
		word = ":page_facing_up:",
		kind = 20,
		label = " 📄 Add or update license",
		documentation = {
			kind = "plaintext",
			value = "(:page_facing_up:)",
		},
		insertText = "📄",
		filterText = ":page_facing_up: Add or update license",
	},
	{
		word = ":boom:",
		kind = 20,
		label = " 💥 Introduce breaking changes",
		documentation = {
			kind = "plaintext",
			value = "(:boom:)",
		},
		insertText = "💥",
		filterText = ":boom: Introduce breaking changes",
	},
	{
		word = ":bento:",
		kind = 20,
		label = " 🍱 Add or update assets",
		documentation = {
			kind = "plaintext",
			value = "(:bento:)",
		},
		insertText = "🍱",
		filterText = ":bento: Add or update assets",
	},
	{
		word = ":wheelchair:",
		kind = 20,
		label = " ♿️ Improve accessibility",
		documentation = {
			kind = "plaintext",
			value = "(:wheelchair:)",
		},
		insertText = "♿️",
		filterText = ":wheelchair: Improve accessibility",
	},
	{
		word = ":bulb:",
		kind = 20,
		label = " 💡 Add or update comments in source code",
		documentation = {
			kind = "plaintext",
			value = "(:bulb:)",
		},
		insertText = "💡",
		filterText = ":bulb: Add or update comments in source code",
	},
	{
		word = ":beers:",
		kind = 20,
		label = " 🍻 Write code drunkenly",
		documentation = {
			kind = "plaintext",
			value = "(:beers:)",
		},
		insertText = "🍻",
		filterText = ":beers: Write code drunkenly",
	},
	{
		word = ":speech_balloon:",
		kind = 20,
		label = " 💬 Add or update text and literals",
		documentation = {
			kind = "plaintext",
			value = "(:speech_balloon:)",
		},
		insertText = "💬",
		filterText = ":speech_balloon: Add or update text and literals",
	},
	{
		word = ":card_file_box:",
		kind = 20,
		label = " 🗃️ Perform database related changes",
		documentation = {
			kind = "plaintext",
			value = "(:card_file_box:)",
		},
		insertText = "🗃️",
		filterText = ":card_file_box: Perform database related changes",
	},
	{
		word = ":loud_sound:",
		kind = 20,
		label = " 🔊 Add or update logs",
		documentation = {
			kind = "plaintext",
			value = "(:loud_sound:)",
		},
		insertText = "🔊",
		filterText = ":loud_sound: Add or update logs",
	},
	{
		word = ":mute:",
		kind = 20,
		label = " 🔇 Remove logs",
		documentation = {
			kind = "plaintext",
			value = "(:mute:)",
		},
		insertText = "🔇",
		filterText = ":mute: Remove logs",
	},
	{
		word = ":busts_in_silhouette:",
		kind = 20,
		label = " 👥 Add or update contributor(s)",
		documentation = {
			kind = "plaintext",
			value = "(:busts_in_silhouette:)",
		},
		insertText = "👥",
		filterText = ":busts_in_silhouette: Add or update contributor(s)",
	},
	{
		word = ":children_crossing:",
		kind = 20,
		label = " 🚸 Improve user experience / usability",
		documentation = {
			kind = "plaintext",
			value = "(:children_crossing:)",
		},
		insertText = "🚸",
		filterText = ":children_crossing: Improve user experience / usability",
	},
	{
		word = ":building_contruction:",
		kind = 20,
		label = " 🏗️ Make architectural changes",
		documentation = {
			kind = "plaintext",
			value = "(:building_contruction:)",
		},
		insertText = "🏗️",
		filterText = ":building_contruction: Make architectural changes",
	},
	{
		word = ":iphone:",
		kind = 20,
		label = " 📱 Work on responsive design",
		documentation = {
			kind = "plaintext",
			value = "(:iphone:)",
		},
		insertText = "📱",
		filterText = ":iphone: Work on responsive design",
	},
	{
		word = ":clown:",
		kind = 20,
		label = " 🤡 Mock things",
		documentation = {
			kind = "plaintext",
			value = "(:clown:)",
		},
		insertText = "🤡",
		filterText = ":clown: Mock things",
	},
	{
		word = ":egg:",
		kind = 20,
		label = " 🥚 Add or update an easter egg",
		documentation = {
			kind = "plaintext",
			value = "(:egg:)",
		},
		insertText = "🥚",
		filterText = ":egg: Add or update an easter egg",
	},
	{
		word = ":see_no_evil:",
		kind = 20,
		label = " 🙈 Add or update a .gitignore file",
		documentation = {
			kind = "plaintext",
			value = "(:see_no_evil:)",
		},
		insertText = "🙈",
		filterText = ":see_no_evil: Add or update a .gitignore file",
	},
	{
		word = ":camera_flash:",
		kind = 20,
		label = " 📸 Add or update snapshots",
		documentation = {
			kind = "plaintext",
			value = "(:camera_flash:)",
		},
		insertText = "📸",
		filterText = ":camera_flash: Add or update snapshots",
	},
	{
		word = ":alembic:",
		kind = 20,
		label = " ⚗️  Perform experiments",
		documentation = {
			kind = "plaintext",
			value = "(:alembic:)",
		},
		insertText = "⚗️",
		filterText = ":alembic: Perform experiments",
	},
	{
		word = ":mag:",
		kind = 20,
		label = " 🔍️ Improve SEO",
		documentation = {
			kind = "plaintext",
			value = "(:mag:)",
		},
		insertText = "🔍️",
		filterText = ":mag: Improve SEO",
	},
	{
		word = ":label:",
		kind = 20,
		label = " 🏷️ Add or update types",
		documentation = {
			kind = "plaintext",
			value = "(:label:)",
		},
		insertText = "🏷️",
		filterText = ":label: Add or update types",
	},
	{
		word = ":seedling:",
		kind = 20,
		label = " 🌱 Add or update seed files",
		documentation = {
			kind = "plaintext",
			value = "(:seedling:)",
		},
		insertText = "🌱",
		filterText = ":seedling: Add or update seed files",
	},
	{
		word = ":triangular_flag_on_pole:",
		kind = 20,
		label = " 🚩 Add, update, or remove feature flags",
		documentation = {
			kind = "plaintext",
			value = "(:triangular_flag_on_pole:)",
		},
		insertText = "🚩",
		filterText = ":triangular_flag_on_pole: Add, update, or remove feature flags",
	},
	{
		word = ":goal_net:",
		kind = 20,
		label = " 🥅 Catch errors",
		documentation = {
			kind = "plaintext",
			value = "(:goal_net:)",
		},
		insertText = "🥅",
		filterText = ":goal_net: Catch errors",
	},
	{
		word = ":dizzy:",
		kind = 20,
		label = " 💫 Add or update animations and transitions",
		documentation = {
			kind = "plaintext",
			value = "(:dizzy:)",
		},
		insertText = "💫",
		filterText = ":dizzy: Add or update animations and transitions",
	},
	{
		word = ":wastebucket:",
		kind = 20,
		label = " 🗑️ Deprecate code that needs to be cleaned up",
		documentation = {
			kind = "plaintext",
			value = "(:wastebucket:)",
		},
		insertText = "🗑️",
		filterText = ":wastebucket: Deprecate code that needs to be cleaned up",
	},
	{
		word = ":passport_control:",
		kind = 20,
		label = " 🛂 Work on code related to authorization, roles and permissions",
		documentation = {
			kind = "plaintext",
			value = "(:passport_control:)",
		},
		insertText = "🛂",
		filterText = ":passport_control: Work on code related to authorization, roles and permissions",
	},
	{
		word = ":adhesive_bandage:",
		kind = 20,
		label = " 🩹 Simple fix for a non-critical issue",
		documentation = {
			kind = "plaintext",
			value = "(:adhesive_bandage:)",
		},
		insertText = "🩹",
		filterText = ":adhesive_bandage: Simple fix for a non-critical issue",
	},
	{
		word = ":monocle_face:",
		kind = 20,
		label = " 🧐 Data exploration/inspection",
		documentation = {
			kind = "plaintext",
			value = "(:monocle_face:)",
		},
		insertText = "🧐",
		filterText = ":monocle_face: Data exploration/inspection",
	},
	{
		word = ":coffin:",
		kind = 20,
		label = " ⚰️  Remove dead code",
		documentation = {
			kind = "plaintext",
			value = "(:coffin:)",
		},
		insertText = "⚰️",
		filterText = ":coffin: Remove dead code",
	},
	{
		word = ":test_tube:",
		kind = 20,
		label = " 🧪 Add a failing test",
		documentation = {
			kind = "plaintext",
			value = "(:test_tube:)",
		},
		insertText = "🧪",
		filterText = ":test_tube: Add a failing test",
	},
	{
		word = ":necktie:",
		kind = 20,
		label = " 👔 Add or update business logic",
		documentation = {
			kind = "plaintext",
			value = "(:necktie:)",
		},
		insertText = "👔",
		filterText = ":necktie: Add or update business logic",
	},
	{
		word = ":stethoscope:",
		kind = 20,
		label = " 🩺 Add or update healthcheck",
		documentation = {
			kind = "plaintext",
			value = "(:stethoscope:)",
		},
		insertText = "🩺",
		filterText = ":stethoscope: Add or update healthcheck",
	},
	{
		word = ":bricks:",
		kind = 20,
		label = " 🧱 Infrastructure related changes",
		documentation = {
			kind = "plaintext",
			value = "(:bricks:)",
		},
		insertText = "🧱",
		filterText = ":bricks: Infrastructure related changes",
	},
	{
		word = ":technologist:",
		kind = 20,
		label = " 🧑💻 Improve developer experience",
		documentation = {
			kind = "plaintext",
			value = "(:technologist:)",
		},
		insertText = "🧑💻",
		filterText = ":technologist: Improve developer experience",
	},
	{
		word = ":money_with_wings:",
		kind = 20,
		label = " 💸 Add sponsorships or money related infrastructure",
		documentation = {
			kind = "plaintext",
			value = "(:money_with_wings:)",
		},
		insertText = "💸",
		filterText = ":money_with_wings: Add sponsorships or money related infrastructure",
	},
	{
		word = ":thread:",
		kind = 20,
		label = " 🧵 Add or update code related to multithreading or concurrency",
		documentation = {
			kind = "plaintext",
			value = "(:thread:)",
		},
		insertText = "🧵",
		filterText = ":thread: Add or update code related to multithreading or concurrency",
	},
	{
		word = ":safety_vest:",
		kind = 20,
		label = " 🦺 Add or update code related to validation",
		documentation = {
			kind = "plaintext",
			value = "(:safety_vest:)",
		},
		insertText = "🦺",
		filterText = ":safety_vest: Add or update code related to validation",
	},
}
